### ISSUE TITLE
Users can submit the form even if it has validated with errors

### ISSUE THREAD

**Issue by omaralqasmi** [MuhaddiMu/VuetiForm#4]
I'm facing one issue.
Even if the field validated with error , user still can submit the form!
example:
the field allow for 10 characters
and the user entered 13 characters, the field will display the error but doesn't stop the user from submitting the form

**Comment by MuhaddiMu** [comment]
Hi, @omaralqasmi Thank you for addressing the issue. I have updated the VuetiForm and added the functionality to disable the submit button if there are errors. You can look at http://muhaddimu.github.io/VuetiForm

But, buttons don't include in the provided code you have to manually add the buttons using `<v-btn>`.

To make it work with lazy load, add `:disabled="!Valid"` attribute in `<v-btn>` and it will work. 

Reopen the issue if you have any other concerns 👍
